import './logo/logo-2.svg';
import './hero/line-leyar.svg';
import './testimonial/user-1.png';
import './testimonial/user-2.png';
import './testimonial/user-3.png';
import './testimonial/user-4.png';
import './testimonial/user-5.png';
import './testimonial/video-thumb-1.png';
import './testimonial/video-thumb-2.png';
import './footer/bg-img.svg';
import './hero/test.png';
import './hero/partenaires/EMECEF.jpg';
import './hero/partenaires/visa.png';
import './hero/partenaires/Mastercard.png';
import './hero/partenaires/mtn.png';
import './hero/partenaires/moov.png';
import './hero/partenaires/UBA.jpg';
import './hero/partenaires/Ecobank.png';
import './benefit/bank.svg';
import './benefit/benefit.png';
import './benefit/contact.svg';
import './benefit/files.svg';
import './benefit/pic.svg';
import './benefit/setting.svg';
import './cta/bg-img.png';
import './blog/author-1.png';
import './blog/author-2.png';
import './blog/blockquote-img.png';
import './blog/blog-single-img-2.png';
import './blog/blog-single-img.png';
import './blog/img-1.png';
import './blog/img-2.png';
import './blog/img-3.png';
import './blog/img-4.png';
import './blog/img-5.png';
import './blog/img-6.png';
import './counter/admin.svg';
import './counter/bag.svg';
import './counter/star.svg';
import './features/img-1.png';
import './features/img-2.png';
import './features/img-3.png';

export { default as CtaBg } from './cta/bg-img.png';
export { default as Logo } from './logo/logo-2.svg';
export { default as LineLeyer } from './hero/line-leyar.svg';
export { default as User1 } from './testimonial/user-1.png';
export { default as User2 } from './testimonial/user-2.png';
export { default as User3 } from './testimonial/user-3.png';
export { default as User4 } from './testimonial/user-4.png';
export { default as User5 } from './testimonial/user-5.png';
export { default as VideoThumb1 } from './testimonial/video-thumb-1.png';
export { default as VideoThumb2 } from './testimonial/video-thumb-2.png';
export { default as FooterBg } from './footer/bg-img.svg';
export { default as Test } from './hero/test.png';
export { default as Mtn } from './hero/partenaires/mtn.png';
export { default as Moov } from './hero/partenaires/moov.png';
export { default as Visa } from './hero/partenaires/visa.png';
export { default as Mastercard } from './hero/partenaires/Mastercard.png';
export { default as UBA } from './hero/partenaires/UBA.jpg';
export { default as Emecef } from './hero/partenaires/EMECEF.jpg';
export { default as Ecobank } from './hero/partenaires/Ecobank.png';
export {default as Bank} from './benefit/bank.svg';
export { default as Benefit } from './benefit/benefit.png';
export { default as Contact } from './benefit/contact.svg';
export { default as Files } from './benefit/files.svg';
export { default as Pic } from './benefit/pic.svg';
export { default as Setting } from './benefit/setting.svg';
export { default as Author1 } from './blog/author-1.png';
export { default as Author2 } from './blog/author-2.png';
export { default as BlockquoteImg } from './blog/blockquote-img.png';
export { default as BlogSingleImg } from './blog/blog-single-img.png';
export { default as BlogSingleImg2 } from './blog/blog-single-img-2.png';
export { default as BlogImg1 } from './blog/img-1.png';
export { default as BlogImg2 } from './blog/img-2.png';
export { default as BlogImg3 } from './blog/img-3.png';
export { default as BlogImg4 } from './blog/img-4.png';
export { default as BlogImg5 } from './blog/img-5.png';
export { default as BlogImg6 } from './blog/img-6.png';
export { default as Star } from './counter/star.svg';
export { default as Admin } from './counter/admin.svg';
export { default as Bag } from './counter/bag.svg';
export { default as FeatureImg1 } from './features/img-1.png';
export { default as FeatureImg2 } from './features/img-2.png';
export { default as FeatureImg3 } from './features/img-3.png';